name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              name: Update Medium blog posts
              with: 
                max_post_count: "5"
                feed_list: "https://medium.com/feed/@xeladu"
            - uses: gautamkrishnar/blog-post-workflow@master
              name: Update QuickCoder blog posts
              with: 
                max_post_count: "5"
                feed_list: "https://quickcoder.org/feed/"
                comment_tag_name: "QC-BLOG-POST-LIST"
